Improve FreeBSD workflow error handling and git commands
Updated the FreeBSD workflow to handle package installation errors and modified the git commands for better clarity.

diff --git a/.github/workflows/freebsd.yml b/.github/workflows/freebsd.yml
--- a/.github/workflows/freebsd.yml
+++ b/.github/workflows/freebsd.yml
@@ -16,8 +16,10 @@ jobs:
       - name: Build node modules
         uses: vmactions/freebsd-vm@v1.2.6
         with:
-          run: |
-            # Add __linux define and modify OS string
+          run: |       
+            set -e
+            set -o pipefail
+            
             echo '#define __linux 1' > build.c.temp
             cat build.c >> build.c.temp
             mv build.c.temp build.c
@@ -25,22 +27,32 @@ jobs:
             sed -i.bak 's/clang-18/clang18/' build.c && rm -f build.c.bak
             sed -i.bak 's/clang++-18/clang++18/' build.c && rm -f build.c.bak
             
-            pkg install -y cmake llvm18 libuv v8
+            pkg install -y cmake llvm18 libuv v8 || echo 'cannot install packages, no privileges'
             
             make
-
-            git fetch origin binaries:binaries
+            
+            git fetch --depth 1 origin binaries:binaries
+            
+            mkdir /tmp/node-binaries
+            cp dist/*.node /tmp/node-binaries/
+            cp dist/*.js /tmp/node-binaries/
+            
+            git reset --hard
+            
             git checkout binaries
-            cp dist/*.node .
-            cp dist/*.js .
+            cp /tmp/node-binaries/*.node .
+            git add ./*.node
+            git checkout master docs/index.d.ts && mv docs/index.d.ts .
+            git add index.d.ts
             git status
             git rev-parse master > source_commit
-            git checkout master docs/index.d.ts && mv docs/index.d.ts .
             git config --global user.email "patrick@tamstrup.dk"
             git config --global user.name "Patrick Tamstrup"
-            git commit -a -m "[GitHub Actions] Updated FreeBSD binaries" || true
-            git push "https://tamstrup:${{ secrets.SECRET }}@github.com/${{ github.repository }}" binaries
+            git commit -m "[GitHub Actions] Updated FreeBSD binaries" || true
+            git push origin binaries
             git checkout master -- tests/smoke.js
+            
             npm install ws
             node tests/smoke.js
+
             
